#############################################
# docker-compose.yml  (placer à la racine)  #
#############################################

services:

  # ──────────────────────────
  #  Django + Daphne (ASGI)
  # ──────────────────────────
  web:
    build: .
    container_name: django
    restart: unless-stopped
    # Variables sensibles dans .env (non versionné)
    env_file: .env
    depends_on:
      db:                         # attend MySQL sain
        condition: service_healthy
    volumes:
      - static:/staticfiles       # collectstatic
      - media:/mediafiles         # uploads utilisateur
    networks: [backend]

  # ──────────────────────────
  #  Reverse-proxy Nginx
  # ──────────────────────────
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - static:/staticfiles:ro
      - media:/mediafiles:ro
      - ./compose/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [web]
    ports:
      - "8080:8080"
    networks: [backend]

  # ──────────────────────────
  #  Base de données MySQL 8
  # ──────────────────────────
  db:
    image: mysql:8.3
    container_name: mysql
    restart: unless-stopped
    environment:
      #  ➜ définis-les dans .env
      MYSQL_ROOT_PASSWORD: Root23175@
      MYSQL_DATABASE:      tictactoe_db
      MYSQL_USER:          root
      MYSQL_PASSWORD:     Root23175@
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pRoot23175@"]
      interval: 5s
      retries: 5
    networks: [backend]

# ──────────────────────────
#  Volumes persistants
# ──────────────────────────
volumes:
  static:
  media:
  dbdata:

# ──────────────────────────
#  Réseau privé
# ──────────────────────────
networks:
  backend:
