# Generated by Django 5.2.3 on 2025-07-14 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('last_main_index', models.PositiveIntegerField(blank=True, null=True)),
                ('last_sub_index', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('board', models.CharField(default='         ', max_length=9)),
                ('player_x', models.CharField(blank=True, max_length=255, null=True)),
                ('player_o', models.CharField(blank=True, max_length=255, null=True)),
                ('active_index', models.PositiveIntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=64, null=True)),
                ('last_player', models.CharField(blank=True, max_length=1, null=True)),
                ('total_time_limit', models.IntegerField(default=600)),
                ('time_x', models.IntegerField(default=300)),
                ('time_o', models.IntegerField(default=300)),
                ('remaining_x', models.IntegerField(default=300)),
                ('remaining_o', models.IntegerField(default=300)),
                ('last_move_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(blank=True, max_length=150)),
                ('mode', models.CharField(choices=[('single', 'Single Player'), ('multi', 'Multiplayer')], max_length=10)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=10)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('moves', models.PositiveIntegerField(default=0)),
                ('game_identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_played'],
            },
        ),
        migrations.CreateModel(
            name='SubGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('board', models.CharField(default='         ', max_length=9)),
                ('player_x', models.CharField(blank=True, max_length=255, null=True)),
                ('player_o', models.CharField(blank=True, max_length=255, null=True)),
                ('winner', models.CharField(blank=True, max_length=64, null=True)),
                ('last_move_index', models.PositiveIntegerField(blank=True, null=True)),
                ('last_computer_move', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_games', to='game.game')),
            ],
        ),
    ]
