# Generated by Django 5.1.3 on 2025-06-30 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('last_main_index', models.PositiveIntegerField(blank=True, null=True)),
                ('last_sub_index', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('board', models.CharField(default='         ', max_length=9)),
                ('player_x', models.CharField(blank=True, max_length=255, null=True)),
                ('player_o', models.CharField(blank=True, max_length=255, null=True)),
                ('active_index', models.PositiveIntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=64, null=True)),
                ('last_player', models.CharField(blank=True, max_length=1, null=True)),
                ('time_x', models.IntegerField(default=300)),
                ('time_o', models.IntegerField(default=300)),
                ('remaining_x', models.IntegerField(default=300)),
                ('remaining_o', models.IntegerField(default=300)),
                ('last_move_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('board', models.CharField(default='         ', max_length=9)),
                ('player_x', models.CharField(blank=True, max_length=255, null=True)),
                ('player_o', models.CharField(blank=True, max_length=255, null=True)),
                ('winner', models.CharField(blank=True, max_length=64, null=True)),
                ('last_move_index', models.PositiveIntegerField(blank=True, null=True)),
                ('last_computer_move', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_games', to='game.game')),
            ],
        ),
    ]
