# Generated by Django 5.1.3 on 2025-07-07 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamehistory',
            options={'ordering': ['-date_played']},
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='moves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='result',
            field=models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=10),
        ),
        migrations.AlterField(
            model_name='gamehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
