# Generated by Django 5.2.3 on 2025-07-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gamehistory_options_gamehistory_duration_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='gamehistory',
            name='game_identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
