# Generated by Django 5.1.3 on 2025-03-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgame',
            name='last_computer_move',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
