# Generated by Django 5.1.3 on 2025-03-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_subgame_last_computer_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgame',
            name='last_move_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
