# Generated by Django 5.1.3 on 2025-03-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_subgame_last_move_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_main_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='last_sub_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
