# Generated by Django 5.1.3 on 2025-04-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_last_main_index_game_last_sub_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='room_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
