# Generated by Django 5.1.3 on 2025-04-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_game_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_o',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_x',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
